### ISSUE TITLE
Kerberize cluster

### ISSUE THREAD

**Issue by NithK45** [NithK45/SEBC#12]

**Comment by NithK45** [comment]
Started installing kerberos server and workstation on the cluster

**Comment by NithK45** [comment]
completed installing KDC setup and the users

**Comment by NithK45** [comment]
Enabled kerberos using cloudera manager UI

**Comment by NithK45** [comment]
Ran terasort program with cate user, uploaded results

**Comment by NithK45** [comment]
Ran the pi example with jemaine user, uploaded results

**Comment by NithK45** [comment]
completed the challenge, all files uploaded to the labs folder

**Comment by NithK45** [comment]
completed this lab little late.

**Comment by mfernest** [comment]
Nine days later seems more than a little late, but I do appreciate taking the time to do this work. :-)

**Comment by mfernest** [comment]
For the purpose of the challenge itself I must score this stage as `didNotSubmit`.
