### ISSUE TITLE
Boot Camp Evaluation: No Pass

### ISSUE THREAD

**Issue by mfernest** [NithK45/SEBC#13]
I am sorry to say I cannot offer you a Pass for the lab and challenge work submitted.

Although I took issue with your lab work, as noted in the Issues comments, your challenge work was quite close to successful. My sense is that you had a very great deal to absorb during the week and did very well from that standpoint. There is simply a little more you need to show in a challenge session.

Please feel free to contact me if you would like to retake the challenge. There is no cost associated with it and no need to attend class again.

**Comment by NithK45** [comment]
Thanks for evaluating my work. I would like to retake the challenge and next possible opportunity. Request you to send me the details and i will be ready for that.

My email: nithinkotha@gmail.com, github handle: NithK45, work email: nithin.kotha@bcstechnology.com.au

Thanks again,
Nithin
+61 404255259
