### ISSUE TITLE
Storage labs

### ISSUE THREAD

**Issue by NithK45** [NithK45/SEBC#3]

**Comment by NithK45** [comment]
Started with HDFS Lab: Test HDFS performance, completed and uploaded data to the labs folder.

**Comment by NithK45** [comment]
Completed the "HDFS Lab: Replicate to another cluster" Lab, Distcp taking longer to transfer 500MB file over network, screenshot uploaded to the labs folder.

**Comment by NithK45** [comment]
completed "HDFS Lab: Test HDFS Snapshots", snapshot UI screen dump is uploaded to the labs folder

**Comment by NithK45** [comment]
completed enabling HDFS HA and created CM user, changed admin user role. uploaded screenshots to the labs folder. And the link for cloudera manager is:
http://ec2-34-210-17-89.us-west-2.compute.amazonaws.com:7180/cmf/home

**Comment by mfernest** [comment]
You might have investigated the issues with your replication work a little deeper. This feels like too much focus on getting tasks complete without concerning yourself with learning from them.
