### ISSUE TITLE
YARN/RM Lab

### ISSUE THREAD

**Issue by NithK45** [NithK45/SEBC#4]
Started Yarn lab exercises

**Comment by NithK45** [comment]
Ignored the "Doing the Math" lab as advised.

**Comment by NithK45** [comment]
uploaded the screenshot of static service pools page to the labs folder

**Comment by NithK45** [comment]
Started on  "Tuning for YARN" Lab

**Comment by NithK45** [comment]
Tried with couple of options of changing container memory and number of mappers and reducers. uploaded script, results and  charts screen dump.

**Comment by mfernest** [comment]
I don't know that I'd call two trials much of an effort. You likely end up with a high and low and nothing in between, In other words, you've created a trial to give you exactly the results you're looking for: a high and low, with no meaningful insight into why one is faster or slower than the other.

Also, the chart you captured: did it not make you curious? That's a lot of red.
