### ISSUE TITLE
Security Lab

### ISSUE THREAD

**Issue by NithK45** [NithK45/SEBC#6]

**Comment by NithK45** [comment]
Installed kerberos and integrated with cloudera manager and generated credentials. Below list of files are uploaded to security/labs folder
kadm5.acl.md,
kdc.conf.md,
kinit.md
krb5.conf.md

**Comment by NithK45** [comment]
Tried to finish Sentry lab, but getting strange issue with access cluster with kerberose ticket users, getting the error "ls: SIMPLE authentication is not enabled.  Available:[TOKEN, KERBEROS]", unable to finish it.

Also, Checked hdfs authorization config in cloudera manager, it is pointed to kerberos. 

![image](https://cloud.githubusercontent.com/assets/21057229/25714005/fb97c7a6-3139-11e7-9cf3-1087f453d91b.png)

**Comment by mfernest** [comment]
The error message `SIMPLE authentication is not enabled` tells you Hadoop does not think Kerberos is available. In effect this means the cluster itself has not been integrated with Kerberos. There's no evidence in the lab work that this stage was completed, i.e., the services themselves were not initialized with Kerberos, or did not initialize correctly.
